
if(MSVC)
set(CPACK_GENERATOR "WIX")
set(CPACK_GENERATOR "TBZ2;DEB;RPM")
endif(MSVC)

set(CPACK_WIX_LICENSE_RTF "${CMAKE_CURRENT_SOURCE_DIR}/COPYING")
set(CPACK_WIX_LICENSE_RTF "${CMAKE_CURRENT_SOURCE_DIR}/COPYING")
set(CPACK_WIX_CULTURES "zh-CN;zh-TW;en-US;neutral")
set(CPACK_WIX_UPGRADE_GUID "40F55B4D-A2F3-492F-86E3-AD8626723DB6")
set(CPACK_WIX_PRODUCT_GUID "40F55B4D-A2F3-492F-86E3-AD8626723DB6")
set(CPACK_WIX_PRODUCT_ICON "${CMAKE_CURRENT_SOURCE_DIR}/src/qt/res/icons/bitcoin.ico")

set(CPACK_SOURCE_GENERATOR "TBZ2")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "RCOIN")
SET(CPACK_PACKAGE_VENDOR "rrjj.com")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/COPYING")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "16")
SET(CPACK_PACKAGE_VERSION_PATCH "99")

SET(CPACK_PACKAGE_EXECUTABLES "rcoin-qt" "rcoin-qt")

SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "rcoin core") #required

SET(CPACK_SOURCE_IGNORE_FILES "${CPACK_SOURCE_IGNORE_FILES};${CMAKE_CURRENT_BINARY_DIR};\\\\.git;\\\\.kdev.*;\\\\.travis\\\\.yml")

if(WIN32)
	SET(CPACK_PACKAGE_INSTALL_DIRECTORY "rcoin")
else()
	SET(CPACK_PACKAGE_INSTALL_DIRECTORY "/")
endif()
