
if(MSVC)
set(CPACK_GENERATOR "WIX")
else()
set(CPACK_GENERATOR "DEB;RPM")
endif(MSVC)

set(CPACK_WIX_LICENSE_RTF "${CMAKE_CURRENT_SOURCE_DIR}/COPYING.txt")
set(CPACK_WIX_CULTURES "zh-CN;zh-TW;en-US;neutral")
set(CPACK_WIX_UPGRADE_GUID "51466E44-E687-4152-9ED7-8C3DB72F2C35")
set(CPACK_WIX_PRODUCT_GUID "51466E44-E687-4152-9ED7-8C3DB72f2C35")
set(CPACK_WIX_PRODUCT_ICON "${CMAKE_CURRENT_SOURCE_DIR}/src/qt/res/icons/bitcoin.ico")
set(CPACK_WIX_UI_BANNER "${CMAKE_CURRENT_SOURCE_DIR}/src/qt/res/setup_banner.png")
set(CPACK_WIX_UI_DIALOG "${CMAKE_CURRENT_SOURCE_DIR}/src/qt/res/setup_wellcomepage.png")
set(CPACK_SOURCE_GENERATOR "TBZ2")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "RCOIN")
SET(CPACK_PACKAGE_VENDOR "rrjj.com")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/COPYING.txt")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "16")
SET(CPACK_PACKAGE_VERSION_PATCH "99")

SET(CPACK_PACKAGE_EXECUTABLES "ecoin-qt" "ecoin-qt")

SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "ecoin core") #required

SET(CPACK_SOURCE_IGNORE_FILES "${CPACK_SOURCE_IGNORE_FILES};${CMAKE_CURRENT_BINARY_DIR};\\\\.git;\\\\.kdev.*;\\\\.travis\\\\.yml")

if(WIN32)
	SET(CPACK_PACKAGE_INSTALL_DIRECTORY "ecoin")
else()
	SET(CPACK_PACKAGE_INSTALL_DIRECTORY "/")
endif()
